/*
 * This file is generated by jOOQ.
 */
package ru.bogatov.fdrtstransaction.model.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String ccNum;
    private String merchantName;
    private String dateTime;
    private String category;
    private Float amount;
    private String transNum;
    private OffsetDateTime unixTime;
    private Boolean isFraud;
    private Boolean migrated;

    public TransactionHistory() {}

    public TransactionHistory(TransactionHistory value) {
        this.id = value.id;
        this.ccNum = value.ccNum;
        this.merchantName = value.merchantName;
        this.dateTime = value.dateTime;
        this.category = value.category;
        this.amount = value.amount;
        this.transNum = value.transNum;
        this.unixTime = value.unixTime;
        this.isFraud = value.isFraud;
        this.migrated = value.migrated;
    }

    public TransactionHistory(
        UUID id,
        String ccNum,
        String merchantName,
        String dateTime,
        String category,
        Float amount,
        String transNum,
        OffsetDateTime unixTime,
        Boolean isFraud,
        Boolean migrated
    ) {
        this.id = id;
        this.ccNum = ccNum;
        this.merchantName = merchantName;
        this.dateTime = dateTime;
        this.category = category;
        this.amount = amount;
        this.transNum = transNum;
        this.unixTime = unixTime;
        this.isFraud = isFraud;
        this.migrated = migrated;
    }

    /**
     * Getter for <code>public.transaction_history.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.transaction_history.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.transaction_history.cc_num</code>.
     */
    public String getCcNum() {
        return this.ccNum;
    }

    /**
     * Setter for <code>public.transaction_history.cc_num</code>.
     */
    public void setCcNum(String ccNum) {
        this.ccNum = ccNum;
    }

    /**
     * Getter for <code>public.transaction_history.merchant_name</code>.
     */
    public String getMerchantName() {
        return this.merchantName;
    }

    /**
     * Setter for <code>public.transaction_history.merchant_name</code>.
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * Getter for <code>public.transaction_history.date_time</code>.
     */
    public String getDateTime() {
        return this.dateTime;
    }

    /**
     * Setter for <code>public.transaction_history.date_time</code>.
     */
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * Getter for <code>public.transaction_history.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>public.transaction_history.category</code>.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for <code>public.transaction_history.amount</code>.
     */
    public Float getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>public.transaction_history.amount</code>.
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>public.transaction_history.trans_num</code>.
     */
    public String getTransNum() {
        return this.transNum;
    }

    /**
     * Setter for <code>public.transaction_history.trans_num</code>.
     */
    public void setTransNum(String transNum) {
        this.transNum = transNum;
    }

    /**
     * Getter for <code>public.transaction_history.unix_time</code>.
     */
    public OffsetDateTime getUnixTime() {
        return this.unixTime;
    }

    /**
     * Setter for <code>public.transaction_history.unix_time</code>.
     */
    public void setUnixTime(OffsetDateTime unixTime) {
        this.unixTime = unixTime;
    }

    /**
     * Getter for <code>public.transaction_history.is_fraud</code>.
     */
    public Boolean getIsFraud() {
        return this.isFraud;
    }

    /**
     * Setter for <code>public.transaction_history.is_fraud</code>.
     */
    public void setIsFraud(Boolean isFraud) {
        this.isFraud = isFraud;
    }

    /**
     * Getter for <code>public.transaction_history.migrated</code>.
     */
    public Boolean getMigrated() {
        return this.migrated;
    }

    /**
     * Setter for <code>public.transaction_history.migrated</code>.
     */
    public void setMigrated(Boolean migrated) {
        this.migrated = migrated;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TransactionHistory other = (TransactionHistory) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ccNum == null) {
            if (other.ccNum != null)
                return false;
        }
        else if (!this.ccNum.equals(other.ccNum))
            return false;
        if (this.merchantName == null) {
            if (other.merchantName != null)
                return false;
        }
        else if (!this.merchantName.equals(other.merchantName))
            return false;
        if (this.dateTime == null) {
            if (other.dateTime != null)
                return false;
        }
        else if (!this.dateTime.equals(other.dateTime))
            return false;
        if (this.category == null) {
            if (other.category != null)
                return false;
        }
        else if (!this.category.equals(other.category))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.transNum == null) {
            if (other.transNum != null)
                return false;
        }
        else if (!this.transNum.equals(other.transNum))
            return false;
        if (this.unixTime == null) {
            if (other.unixTime != null)
                return false;
        }
        else if (!this.unixTime.equals(other.unixTime))
            return false;
        if (this.isFraud == null) {
            if (other.isFraud != null)
                return false;
        }
        else if (!this.isFraud.equals(other.isFraud))
            return false;
        if (this.migrated == null) {
            if (other.migrated != null)
                return false;
        }
        else if (!this.migrated.equals(other.migrated))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ccNum == null) ? 0 : this.ccNum.hashCode());
        result = prime * result + ((this.merchantName == null) ? 0 : this.merchantName.hashCode());
        result = prime * result + ((this.dateTime == null) ? 0 : this.dateTime.hashCode());
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.transNum == null) ? 0 : this.transNum.hashCode());
        result = prime * result + ((this.unixTime == null) ? 0 : this.unixTime.hashCode());
        result = prime * result + ((this.isFraud == null) ? 0 : this.isFraud.hashCode());
        result = prime * result + ((this.migrated == null) ? 0 : this.migrated.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TransactionHistory (");

        sb.append(id);
        sb.append(", ").append(ccNum);
        sb.append(", ").append(merchantName);
        sb.append(", ").append(dateTime);
        sb.append(", ").append(category);
        sb.append(", ").append(amount);
        sb.append(", ").append(transNum);
        sb.append(", ").append(unixTime);
        sb.append(", ").append(isFraud);
        sb.append(", ").append(migrated);

        sb.append(")");
        return sb.toString();
    }
}
