/*
 * This file is generated by jOOQ.
 */
package ru.bogatov.fdrtscore.model.database.jooq.tables.pojos;


import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String ccNum;
    private String firstName;
    private String lastName;
    private Boolean gender;
    private LocalDate birthday;
    private String street;
    private String city;
    private String state;
    private Integer zip;
    private String job;
    private Integer cityPop;
    private Float lat;
    private Float long_;
    private Boolean migrated;

    public Customer() {}

    public Customer(Customer value) {
        this.id = value.id;
        this.ccNum = value.ccNum;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.gender = value.gender;
        this.birthday = value.birthday;
        this.street = value.street;
        this.city = value.city;
        this.state = value.state;
        this.zip = value.zip;
        this.job = value.job;
        this.cityPop = value.cityPop;
        this.lat = value.lat;
        this.long_ = value.long_;
        this.migrated = value.migrated;
    }

    public Customer(
        UUID id,
        String ccNum,
        String firstName,
        String lastName,
        Boolean gender,
        LocalDate birthday,
        String street,
        String city,
        String state,
        Integer zip,
        String job,
        Integer cityPop,
        Float lat,
        Float long_,
        Boolean migrated
    ) {
        this.id = id;
        this.ccNum = ccNum;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.birthday = birthday;
        this.street = street;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.job = job;
        this.cityPop = cityPop;
        this.lat = lat;
        this.long_ = long_;
        this.migrated = migrated;
    }

    /**
     * Getter for <code>public.customer.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.customer.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.customer.cc_num</code>.
     */
    public String getCcNum() {
        return this.ccNum;
    }

    /**
     * Setter for <code>public.customer.cc_num</code>.
     */
    public void setCcNum(String ccNum) {
        this.ccNum = ccNum;
    }

    /**
     * Getter for <code>public.customer.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>public.customer.first_name</code>.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for <code>public.customer.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>public.customer.last_name</code>.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for <code>public.customer.gender</code>.
     */
    public Boolean getGender() {
        return this.gender;
    }

    /**
     * Setter for <code>public.customer.gender</code>.
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * Getter for <code>public.customer.birthday</code>.
     */
    public LocalDate getBirthday() {
        return this.birthday;
    }

    /**
     * Setter for <code>public.customer.birthday</code>.
     */
    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }

    /**
     * Getter for <code>public.customer.street</code>.
     */
    public String getStreet() {
        return this.street;
    }

    /**
     * Setter for <code>public.customer.street</code>.
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * Getter for <code>public.customer.city</code>.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>public.customer.city</code>.
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>public.customer.state</code>.
     */
    public String getState() {
        return this.state;
    }

    /**
     * Setter for <code>public.customer.state</code>.
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Getter for <code>public.customer.zip</code>.
     */
    public Integer getZip() {
        return this.zip;
    }

    /**
     * Setter for <code>public.customer.zip</code>.
     */
    public void setZip(Integer zip) {
        this.zip = zip;
    }

    /**
     * Getter for <code>public.customer.job</code>.
     */
    public String getJob() {
        return this.job;
    }

    /**
     * Setter for <code>public.customer.job</code>.
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * Getter for <code>public.customer.city_pop</code>.
     */
    public Integer getCityPop() {
        return this.cityPop;
    }

    /**
     * Setter for <code>public.customer.city_pop</code>.
     */
    public void setCityPop(Integer cityPop) {
        this.cityPop = cityPop;
    }

    /**
     * Getter for <code>public.customer.lat</code>.
     */
    public Float getLat() {
        return this.lat;
    }

    /**
     * Setter for <code>public.customer.lat</code>.
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * Getter for <code>public.customer.long</code>.
     */
    public Float getLong() {
        return this.long_;
    }

    /**
     * Setter for <code>public.customer.long</code>.
     */
    public void setLong(Float long_) {
        this.long_ = long_;
    }

    /**
     * Getter for <code>public.customer.migrated</code>.
     */
    public Boolean getMigrated() {
        return this.migrated;
    }

    /**
     * Setter for <code>public.customer.migrated</code>.
     */
    public void setMigrated(Boolean migrated) {
        this.migrated = migrated;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Customer other = (Customer) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ccNum == null) {
            if (other.ccNum != null)
                return false;
        }
        else if (!this.ccNum.equals(other.ccNum))
            return false;
        if (this.firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!this.firstName.equals(other.firstName))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        if (this.gender == null) {
            if (other.gender != null)
                return false;
        }
        else if (!this.gender.equals(other.gender))
            return false;
        if (this.birthday == null) {
            if (other.birthday != null)
                return false;
        }
        else if (!this.birthday.equals(other.birthday))
            return false;
        if (this.street == null) {
            if (other.street != null)
                return false;
        }
        else if (!this.street.equals(other.street))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        if (this.zip == null) {
            if (other.zip != null)
                return false;
        }
        else if (!this.zip.equals(other.zip))
            return false;
        if (this.job == null) {
            if (other.job != null)
                return false;
        }
        else if (!this.job.equals(other.job))
            return false;
        if (this.cityPop == null) {
            if (other.cityPop != null)
                return false;
        }
        else if (!this.cityPop.equals(other.cityPop))
            return false;
        if (this.lat == null) {
            if (other.lat != null)
                return false;
        }
        else if (!this.lat.equals(other.lat))
            return false;
        if (this.long_ == null) {
            if (other.long_ != null)
                return false;
        }
        else if (!this.long_.equals(other.long_))
            return false;
        if (this.migrated == null) {
            if (other.migrated != null)
                return false;
        }
        else if (!this.migrated.equals(other.migrated))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ccNum == null) ? 0 : this.ccNum.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.gender == null) ? 0 : this.gender.hashCode());
        result = prime * result + ((this.birthday == null) ? 0 : this.birthday.hashCode());
        result = prime * result + ((this.street == null) ? 0 : this.street.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.zip == null) ? 0 : this.zip.hashCode());
        result = prime * result + ((this.job == null) ? 0 : this.job.hashCode());
        result = prime * result + ((this.cityPop == null) ? 0 : this.cityPop.hashCode());
        result = prime * result + ((this.lat == null) ? 0 : this.lat.hashCode());
        result = prime * result + ((this.long_ == null) ? 0 : this.long_.hashCode());
        result = prime * result + ((this.migrated == null) ? 0 : this.migrated.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customer (");

        sb.append(id);
        sb.append(", ").append(ccNum);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(gender);
        sb.append(", ").append(birthday);
        sb.append(", ").append(street);
        sb.append(", ").append(city);
        sb.append(", ").append(state);
        sb.append(", ").append(zip);
        sb.append(", ").append(job);
        sb.append(", ").append(cityPop);
        sb.append(", ").append(lat);
        sb.append(", ").append(long_);
        sb.append(", ").append(migrated);

        sb.append(")");
        return sb.toString();
    }
}
