/*
 * This file is generated by jOOQ.
 */
package ru.bogatov.fdrtscore.model.database.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Merchant implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String name;
    private Float lat;
    private Float long_;

    public Merchant() {}

    public Merchant(Merchant value) {
        this.id = value.id;
        this.name = value.name;
        this.lat = value.lat;
        this.long_ = value.long_;
    }

    public Merchant(
        UUID id,
        String name,
        Float lat,
        Float long_
    ) {
        this.id = id;
        this.name = name;
        this.lat = lat;
        this.long_ = long_;
    }

    /**
     * Getter for <code>public.merchant.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.merchant.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.merchant.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.merchant.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.merchant.lat</code>.
     */
    public Float getLat() {
        return this.lat;
    }

    /**
     * Setter for <code>public.merchant.lat</code>.
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * Getter for <code>public.merchant.long</code>.
     */
    public Float getLong() {
        return this.long_;
    }

    /**
     * Setter for <code>public.merchant.long</code>.
     */
    public void setLong(Float long_) {
        this.long_ = long_;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Merchant other = (Merchant) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.lat == null) {
            if (other.lat != null)
                return false;
        }
        else if (!this.lat.equals(other.lat))
            return false;
        if (this.long_ == null) {
            if (other.long_ != null)
                return false;
        }
        else if (!this.long_.equals(other.long_))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.lat == null) ? 0 : this.lat.hashCode());
        result = prime * result + ((this.long_ == null) ? 0 : this.long_.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Merchant (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(lat);
        sb.append(", ").append(long_);

        sb.append(")");
        return sb.toString();
    }
}
