


spring:


  datasource:
    url: jdbc:postgresql://localhost:5432/fdrts
    username: postgres
    password: 12345678

  jooq:
    sql-dialect: postgres

  application:
    name: fdrts-core

  rabbitmq:
    host: localhost
    username: admin
    password: admin

  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB


