/*
 * This file is generated by jOOQ.
 */
package ru.bogatov.fdrtcore.model.database.jooq;


import ru.bogatov.fdrtcore.model.database.jooq.tables.Customer;
import ru.bogatov.fdrtcore.model.database.jooq.tables.Merchant;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.merchant</code>.
     */
    public static final Merchant MERCHANT = Merchant.MERCHANT;
}
