/*
 * This file is generated by jOOQ.
 */
package ru.bogatov.fdrtstransaction.model.dto.migration;



import lombok.Data;

import java.time.OffsetDateTime;
import java.util.UUID;


@Data
public class TransactionDto {

    private UUID id;
    private String ccNum;
    private String merchantName;
    private String dateTime;
    private String category;
    private Float amount;
    private String transNum;
    private OffsetDateTime unixTime;
    private Boolean isFraud;
    private Boolean migrated;
    private Boolean validate;

}
