/*
 * This file is generated by jOOQ.
 */
package ru.bogatov.fdrtscore.model.dto;



import lombok.Data;

import java.time.OffsetDateTime;
import java.util.UUID;


@Data
public class TransactionEvent {

    private UUID id;
    private String ccNum;
    private String merchantName;
    private String dateTime;
    private Integer category;
    private Float amount;
    private String transNum;
    private String categoryName;
    private Float ccLat;
    private Float ccLong;
    private Float merchLat;
    private Float merchLong;
    private Integer cityPop;
    private OffsetDateTime unixTime;
    private Boolean isFraud;
    private Boolean migrated;
    private Boolean validate;

}
