/*
 * This file is generated by jOOQ.
 */
package ru.bogatov.fdrtstransaction.model.database.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.bogatov.fdrtstransaction.model.database.jooq.tables.TransactionHistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.transaction_history</code>.
     */
    public final TransactionHistory TRANSACTION_HISTORY = TransactionHistory.TRANSACTION_HISTORY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TransactionHistory.TRANSACTION_HISTORY
        );
    }
}
