/*
 * This file is generated by jOOQ.
 */
package ru.bogatov.fdrtstransaction.model.database.jooq;


import ru.bogatov.fdrtstransaction.model.database.jooq.tables.TransactionHistory;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.transaction_history</code>.
     */
    public static final TransactionHistory TRANSACTION_HISTORY = TransactionHistory.TRANSACTION_HISTORY;
}
